language: csharp
dist: trusty
sudo: required
mono: latest
dotnet: 1.0.1
solution: Core.Shogi.csproj

before_install:
  - REPO_COMMIT_AUTHOR=$(git show -s --pretty=format:"%cn")
  - REPO_COMMIT_AUTHOR_EMAIL=$(git show -s --pretty=format:"%ce")
  - REPO_COMMIT_MESSAGE=$(git show -s --pretty=format:"%s")
  - chmod +x build.sh

install:
  - dotnet restore -v d --packages ./packages

script:
  - which dotnet
  - ./build.sh
 # - dotnet build 
  - dotnet test Core.Shogi.Tests/Core.Shogi.Tests.csproj
  - mono ./packages/opencover/4.6.519/tools/OpenCover.Console.exe -target:"dotnet.exe" -targetargs:"test Core.Shogi.Tests/Core.Shogi.Tests.csproj" -output:coverage.xml -register:user -filter:"+[*]* -[xunit*]* -[*.Program]*" -oldStyle -log:Off
  - mono ./packages/coveralls.net/0.8.0-unstable0013/tools/csmacnz.Coveralls.exe --opencover -i ./coverage.xml --repoToken $COVERALLS_TOKEN --commitId $TRAVIS_COMMIT --commitBranch $TRAVIS_BRANCH --commitAuthor "$REPO_COMMIT_AUTHOR" --commitEmail "$REPO_COMMIT_AUTHOR_EMAIL" --commitMessage "$REPO_COMMIT_MESSAGE" --jobId $TRAVIS_JOB_ID --serviceName "travis-ci" --useRelativePaths